### ISSUE TITLE
preservation object handler service method for create (blocked by #65)

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_core_catalog#113] opened 2017-09-21 21:02 UTC
something that does the right default stuff for creating a new catalog entry:
* create the preserved_object
* create the online preservation_copy
* give it a default preservation_policy
* whatever else

**Comment by ndushay** [comment] 2017-09-29 00:46
duplicate of #131;  closing.

**Closed by ndushay** 2017-09-29 00:46 UTC
Labels: blocked, ready
