### ISSUE TITLE
PCC: consider revising db schema per Julian's diagram

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_core_catalog#38] opened 2017-08-28 18:25 UTC
Current db schema and Julian's have some differences;  discuss with Julian and adjust ours as warranted.

**Comment by ndushay** [comment] 2017-08-28 23:46
See also #46 -- is one of these a dup?

**Comment by jmartin-sul** [comment] 2017-08-29 20:56
closing this as a duplicate of #46:  normally i'd keep the first one open, but the new one already has @julianmorley's diagram on it, so will leave that one open.

**Closed** 2017-08-29 23:43 UTC
